Basic Player Movement + Jump
FurballCat/Artemis pull request #11
Opened 2022-10-11 19:20 UTC by Arvi-beep-boop

Few components, rigidbody, character controller, floor added

2022-10-11 21:54 UTC, AdamAure requested changes
Good job! It works but has some bugs. I left comments for style (minor) and functionality + how to fix jumping and gravity bugs.
Bug #1: wait a while, then walk off the world's edge - see that you fall super fast (like a crazy bat!).
Bug #2: jumping is unpredictable, sometimes low, sometimes high.

2022-10-11 21:54 UTC, AdamAure commented on Assets/PlayerMovement.cs
> +        }
Define an action in "project settings > input" for jumping. Accessing specific keys in code could work for debug code, but not for gameplay code (we need gamepad or custom bindings for the keyboard in games).

As for jumpHeight - right now you set the velocity. I like the idea of defining jump height. Can you think about how to calculate the velocity based on jump height and gravity? It's a bit of Newtonian physics, google it :D

2022-10-11 21:54 UTC, AdamAure commented on Assets/PlayerMovement.cs
> +        controller.Move(move * Time.deltaTime * playerSpeed);
First, calculate velocity, then call controller.Move once. Reason: every Move is instantly doing a physics check (slide and collide). You can verify this by logging transform.position before and after Move call. There's no reason to call move first for horizontal movement, then another move for vertical movement.

2022-10-11 21:54 UTC, AdamAure commented on Assets/PlayerMovement.cs
> +        controller.Move(playerVelocity * Time.deltaTime);
There's a bug here. If you wait for a while and walk off the world's edge, the capsule has high y speed in the down direction. This is because gravity is accumulated even though the character is grounded. While grounded, you can set playerVelocity.y = 0.0f; However, remember that then you need to swap the order of applying jump velocity and gravity. So the final order is:
if grounded then y == 0 else y += gravity;
if jump and grounded then y += jump;

This will also fix jumping height, as right now, the jump is sometimes high, sometimes low.

2022-10-11 21:54 UTC, AdamAure commented on Assets/PlayerMovement.cs
> +        }
Oh, nice one! I didn't know you could do that in Unity to set an object's direction.

2022-10-12 12:26 UTC, Arvi-beep-boop commented on Assets/PlayerMovement.cs
> +        }
Actually found that one in Unity documentation about Character Controller

2022-10-12 18:01 UTC, merged